cookie:
  expiry_days: 30
  key: "super_secret_alphalitical_cookie_key_123!"
  name: "alpha_scraper_cookie"

credentials:
  usernames:
    adminalpha:
      email: "admin@alphalitical.com"
      name: "admin"
      password: "$2b$12$4IkGWajQFYeNAC5e/r9Nse3n3NTLkrKSaUrCFRj6CJNs6KOfufU6y"
      roles: 
        - "admin"
      logged_in: False
      failed_login_attempts: 0

    editoralpha:
      email: "editor@alphalitical.com"
      name: "editor"
      password: "$2b$12$y3nb87vQ13oICANmAi/1iu2FZYr9X4i84bHFK.gdE/WKu9EiH9gHS"
      roles:
        - "editor"
      logged_in: False
      failed_login_attempts: 0

    vieweralpha:
      email: "viewer@alphalitical.com"
      name: "viewer"
      password: "$2b$12$kNWzYD95/Svf1aW8MjtQL.mN0uN7ikJZjBGoL.xqZ5DuHGd9aMRHu"
      roles:
        - "viewer"
      logged_in: False
      failed_login_attempts: 0

pre-authorized:
  emails:
    - "admin@alphalitical.com"
    - "editor@alphalitical.com"
    - "viewer@alphalitical.com"